### ISSUE TITLE
Захардкоженный шрифт

### ISSUE THREAD

**Issue by viktor02** [Infqq/simpledemotivators#21]
Я правильно понимаю, что шрифт arialbd.ttf захардкожен в[ коде](https://github.com/Infqq/simpledemotivators/blob/8b858b11e3a1243f7e61981619409f40d7d600b4/simpledemotivators/Quote.py#L32) и мои настройки не влияют на него?

```python
if choice == '1':
  # В демотиваторе шрифт применяется
  dem = Demotivator(request.form.get('text'), request.form.get('subtext'))
  dem.create(inp_filepath, fonttext=app.config['FONT_PATH'], RESULT_FILENAME=out_filepath)
elif choice == '2':
  # В Quote выдает ошибку, что шрифт arialbd.ttf не найден
  quote = Quote(request.form.get('text'), request.form.get('subtext'))
  quote.get(inp_filepath, name_font=app.config['FONT_PATH'], text_font=app.config['FONT_PATH'],  RESULT_FILENAME=out_filepath)
```
```
Traceback (most recent call last):
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
Jul 24 21:28:17 vitka-k bash[412]:     return self.wsgi_app(environ, start_response)
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
Jul 24 21:28:17 vitka-k bash[412]:     response = self.handle_exception(e)
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
Jul 24 21:28:17 vitka-k bash[412]:     response = self.full_dispatch_request()
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
Jul 24 21:28:17 vitka-k bash[412]:     rv = self.handle_user_exception(e)
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
Jul 24 21:28:17 vitka-k bash[412]:     rv = self.dispatch_request()
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
Jul 24 21:28:17 vitka-k bash[412]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 24 21:28:17 vitka-k bash[412]:   File "app.py", line 70, in upload_file
Jul 24 21:28:17 vitka-k bash[412]:     quote.get(inp_filepath, name_font=app.config['FONT_PATH'], text_font=app.config['FONT_PATH'], RESULT_FILENAME=out_fil
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/simpledemotivators/Quote.py", line 32, in get
Jul 24 21:28:17 vitka-k bash[412]:     font_1 = ImageFont.truetype(font='arialbd.ttf', size=40, encoding='UTF-8')
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 853, in truetype
Jul 24 21:28:17 vitka-k bash[412]:     return freetype(font)
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 850, in freetype
Jul 24 21:28:17 vitka-k bash[412]:     return FreeTypeFont(font, size, index, encoding, layout_engine)
Jul 24 21:28:17 vitka-k bash[412]:   File "/root/demotivator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 210, in __init__
Jul 24 21:28:17 vitka-k bash[412]:     font, size, index, encoding, layout_engine=layout_engine
Jul 24 21:28:17 vitka-k bash[412]: OSError: cannot open resource
```
p.s. да, я знаю, что можно его установить отдельно, однако было бы лучше, если бы его можно было менять

**Comment by Infqq** [comment]
Если еще актуально, то пересоздайте Issue.
