### ISSUE TITLE
Отсутствие фикса для версии 2.0.1

### ISSUE THREAD

**Issue by Alcash228** [Infqq/simpledemotivators#23]
Я столкнулся с проблемой.

Traceback (most recent call last): File "/data/data/com.termux/files/home/123434.py", line 106, in <module>
dem.create(attachs[0]['photo']['sizes'][-1]['url'],url = True, line='@neuroizh',fonttext='arial.ttf', RESULT_FILENAME='dem.png')
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/simpledemotivators/Demotivator.py", line 56, in create
font_1 = ImageFont.truetype(font=fonttext, size=size2, encoding='UTF-8') File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 853, in truetype return freetype(font)
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 850, in freetype return FreeTypeFont(font, size, index, encoding, layout_engine) File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 209, in __init__
self.font = core.getfont( OSError: unknown file format

Я пробовал поставить heroku fix, но там нет последней версии, а только 1.8.0 

OS: Linux

Прошу вашей помощи, буду очень признателен

**Comment by Alcash228** [comment]
Если я не указываю свой шрифт, ошибка:

Traceback (most recent call last):
File "/data/data/com.termux/files/home/123434.py", line 106, in <module>
dem.create(attachs[0]['photo']['sizes'][-1]['url'],url = True, line='@neuroizh', RESULT_FILENAME='dem.png')
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/simpledemotivators/Demotivator.py", line 56, in create
font_1 = ImageFont.truetype(font=fonttext, size=size2, encoding='UTF-8')
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 853, in truetype
return freetype(font)
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 850, in freetype
return FreeTypeFont(font, size, index, encoding, layout_engine)
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 209, in __init__
self.font = core.getfont(
OSError: cannot open resource

**Comment by Ron788** [comment]
Так, автор проекта давно уже не активит, исправлять некому.
Шрифт в коде оставляй какой был, но только в папку проекта закинь файл шрифта (можно любой скачанный с интернета) с названием ".ttf"

**Comment by Alcash228** [comment]
Я добавлял в папку файл со шрифтом, и у меня ошибка 
self.font = core.getfont( OSError: unknown file format

**Comment by Ron788** [comment]
Возможно ты скачал шрифт в другом формате, не ttf

**Comment by BlitGaming** [comment]
> Возможно ты скачал шрифт в другом формате, не ttf.
> И вообще, библиотеку нужно дорабатывать, ведь автор перестал активить...

Кстати да, почему ещё никто не довел её до нормального состояния? Форков много, но изменений нет

**Comment by Infqq** [comment]
Нужно указать перед названием шрифта: /app/
Фикс будет только после 21 числа, сейчас в другом городе
