### ISSUE TITLE
 ImportError: cannot import name 'demcreate' from 'simpledemotivators'

### ISSUE THREAD

**Issue by Creveoolus** [Infqq/simpledemotivators#24]
`2021-08-17T18:30:17.668725+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-17T18:30:17.669306+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
2021-08-17T18:30:17.670780+00:00 app[worker.1]:     spec.loader.exec_module(lib)
2021-08-17T18:30:17.670809+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2021-08-17T18:30:17.671098+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-08-17T18:30:17.671300+00:00 app[worker.1]:   File "/app/cogs/canvas.py", line 12, in <module>
2021-08-17T18:30:17.671623+00:00 app[worker.1]:     from simpledemotivators import demcreate
2021-08-17T18:30:17.671972+00:00 app[worker.1]: ImportError: cannot import name 'demcreate' from 'simpledemotivators' (/app/.heroku/python/lib/python3.7/site-packages/simpledemotivators/__init__.py)
2021-08-17T18:30:17.671998+00:00 app[worker.1]: 
2021-08-17T18:30:17.671998+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-08-17T18:30:17.671999+00:00 app[worker.1]: 
2021-08-17T18:30:17.672021+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-17T18:30:17.672052+00:00 app[worker.1]:   File "main.py", line 83, in <module>
2021-08-17T18:30:17.672583+00:00 app[worker.1]:     client.load_extension(f'cogs.{filename[:-3]}')
2021-08-17T18:30:17.672634+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
2021-08-17T18:30:17.673995+00:00 app[worker.1]:     self._load_from_module_spec(spec, name)
2021-08-17T18:30:17.674424+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
2021-08-17T18:30:17.676217+00:00 app[worker.1]:     raise errors.ExtensionFailed(key, e) from e
 discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.canvas' raised an error: ImportError: cannot import name 'demcreate' from 'simpledemotivators' (/app/.heroku/python/lib/python3.7/site-packages/simpledemotivators/__init__.py)`

что изменилось?

**Comment by Creveoolus** [comment]
как всегда, скачивал фикс для хероку, а тут такое

**Comment by Ron788** [comment]
Я только заметил, автор слил стандартную ветку в heroku-fix и она теперь бессмысленна. Вообще автор перестал активить и надеется на исправление не стоит.

**Comment by Infqq** [comment]
Проблема актуальна?
