### ISSUE TITLE
какаята хуита

### ISSUE THREAD

**Issue by SavokBS** [Infqq/simpledemotivators#35]
Traceback (most recent call last):
        File "C:\Users\savok\AppData\Local\Temp\pip-install-_c_fdgsj\pillow_6f718414c7de49ffa7c347fc5c49fa33\setup.py", line 976, in <module>
          setup(
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
          self.run_command('build')
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\savok\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\savok\AppData\Local\Temp\pip-install-_c_fdgsj\pillow_6f718414c7de49ffa7c347fc5c49fa33\setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\savok\AppData\Local\Temp\pip-install-_c_fdgsj\pillow_6f718414c7de49ffa7c347fc5c49fa33\setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      C:\Users\savok\AppData\Local\Temp\pip-install-_c_fdgsj\pillow_6f718414c7de49ffa7c347fc5c49fa33\setup.py:46: RuntimeWarning: Pillow 8.2.0 does not support Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\savok\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of pillow
  Moving to c:\users\savok\appdata\local\programs\python\python310\lib\site-packages\pil\
   from C:\Users\savok\AppData\Local\Programs\Python\Python310\Lib\site-packages\~il
  Moving to c:\users\savok\appdata\local\programs\python\python310\lib\site-packages\pillow-9.0.1.dist-info\
   from C:\Users\savok\AppData\Local\Programs\Python\Python310\Lib\site-packages\~illow-9.0.1.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

че делать а !

**Comment by BlitGaming** [comment]
- Попробуй другие версии питона, например, 3.10 или 3.7 или любые другие. У меня на последней всё ставилось

**Comment by ili321** [comment]
такая же хуйня

**Comment by Ron788** [comment]
Плс, научитесь читать ошибки. Сказано же, что версия pillow 8.2.0 не поддерживается питоном версии 3.10, а значит просто надо просто: изменить версию в коде библиотеки (setup.py). Но сначала я это проверю
