### ISSUE TITLE
Не распознает шрифт

### ISSUE THREAD

**Issue by Creveoolus** [Infqq/simpledemotivators#7]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/cogs/canvas.py", line 489, in demotivator
    dem.setline('Lucifer Bot')
  File "/app/.heroku/python/lib/python3.7/site-packages/simpledemotivators/__init__.py", line 70, in setline
    font_2 = ImageFont.truetype(font=fonttext, size=20, encoding='UTF-8')
  File "/app/.heroku/python/lib/python3.7/site-packages/PIL/ImageFont.py", line 853, in truetype
    return freetype(font)
  File "/app/.heroku/python/lib/python3.7/site-packages/PIL/ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/app/.heroku/python/lib/python3.7/site-packages/PIL/ImageFont.py", line 210, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/jishaku/cog_base.py", line 358, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OSError: cannot open resource

Что это за хуйня. Я проебал день на эту ошибку, нихуя не помогло.
ОС: Linux
Я еще специально сделал форк, чтобы потыкать ченить. НИХУЯ. Разработчик, как мне это пофиксить?
Буду очень признателен если поможешь. Если есть дискорд, то прошу напиши мне туда, будет удобнее: ### Creve#0001

**Comment by Creveoolus** [comment]
Creve#0001

**Comment by Infqq** [comment]
Как я понял heroku у вас?

**Comment by Creveoolus** [comment]
> Как я понял heroku у вас?

да

**Comment by Infqq** [comment]
Вечером отпишу вам, как сделаю фикс. (18:00 мск)

**Comment by Creveoolus** [comment]
> Вечером отпишу вам, как сделаю фикс. (18:00 мск)

уже 23:30, кхм

**Comment by Infqq** [comment]
Извиняюсь, не успел

**Comment by Creveoolus** [comment]
> Извиняюсь, не успел

Фикс хотябы готов?

**Comment by Infqq** [comment]
> > Извиняюсь, не успел
> 
> Фикс хотябы готов?

Попробуйте apt-get install msttcorefonts

Если не поможет, залью фикс версию.

**Comment by Infqq** [comment]
pip3 install https://github.com/Infqq/simpledemotivators/archive/heroku-fix.zip --upgrade

**Comment by Infqq** [comment]
+ Надо скачать шрифт (times.ttf), закинуть его в репозиторий вашего бота/проекта

**Comment by Creveoolus** [comment]
Спасибо, сейчас протестирую

**Comment by Creveoolus** [comment]
Все работает, спасибо огромное! <3

**Comment by Infqq** [comment]
@Creveoolus извиняюсь, какой именно способ помог? (Нужно для документации)

**Comment by Creveoolus** [comment]
Всм какой, который пач

**Comment by Infqq** [comment]
> Всм какой, который пач

pip3 install https://github.com/Infqq/simpledemotivators/archive/heroku-fix.zip --upgrade это помогло?

**Comment by Creveoolus** [comment]
> pip3 install https://github.com/Infqq/simpledemotivators/archive/heroku-fix.zip --upgrade

вот вот этот помог

**Comment by Creveoolus** [comment]
> > Всм какой, который пач
> 
> pip3 install https://github.com/Infqq/simpledemotivators/archive/heroku-fix.zip --upgrade это помогло?

да

**Comment by Infqq** [comment]
Спасибо за ответ! 
Закрыто.
